@B2BCustomers.API_HostAddress = http://localhost:5289

GET {{B2BCustomers.API_HostAddress}}/openapi/v1.json
Accept: application/json

###

GET {{B2BCustomers.API_HostAddress}}/weatherforecast/
Accept: application/json

###
